name = "sukima-ml"
compatibility_date = "2024-11-10"

[assets]
directory = "./build"

[env.production]
name = "sukima-ml"
compatibility_date = "2024-11-10"

[env.production.assets]
directory = "./build"