name = "sukimaml"
compatibility_date = "2024-11-10"

[assets]
directory = "./build"


# Production 环境 (若有差异再配置)
# [env.production]
# name = "sukima-ml"
# compatibility_date = "2024-11-10"
# [env.production.assets]
# directory = "./build"